# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'Player' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Player
  pod 'Firebase'
  pod 'Firebase/Database'

end

target 'PlayerTV' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PlayerTV
  pod 'Firebase'

end
